/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-tint": "#865300",
        "tertiary": "#5e5e5e",
        "secondary": "#745b18",
        "primary-fixed": "#ffddb9",
        "on-secondary-fixed-variant": "#5a4300",
        "on-error-container": "#93000a",
        "background": "#f9faf3",
        "tertiary-container": "#a3a2a2",
        "surface-dim": "#d9dbd4",
        "on-secondary-fixed": "#251a00",
        "secondary-container": "#ffdc8c",
        "on-tertiary-container": "#393939",
        "on-primary": "#ffffff",
        "primary-fixed-dim": "#ffb962",
        "inverse-primary": "#ffb962",
        "primary-container": "#db9435",
        "error": "#ba1a1a",
        "tertiary-fixed": "#e4e2e2",
        "surface-container-highest": "#e2e3dc",
        "surface-container-low": "#f3f4ed",
        "surface-container-high": "#e8e9e2",
        "on-secondary-container": "#795f1d",
        "surface-bright": "#f9faf3",
        "surface-container": "#edeee7",
        "tertiary-fixed-dim": "#c8c6c6",
        "inverse-on-surface": "#f0f1ea",
        "on-tertiary-fixed": "#1b1c1c",
        "on-primary-fixed": "#2b1700",
        "on-error": "#ffffff",
        "inverse-surface": "#2f312d",
        "on-tertiary": "#ffffff",
        "on-surface-variant": "#524436",
        "error-container": "#ffdad6",
        "primary": "#865300",
        "outline-variant": "#d7c3b1",
        "surface": "#f9faf3",
        "on-primary-container": "#533200",
        "secondary-fixed": "#ffdf99",
        "on-tertiary-fixed-variant": "#474747",
        "surface-container-lowest": "#ffffff",
        "on-secondary": "#ffffff",
        "on-primary-fixed-variant": "#663e00",
        "outline": "#847464",
        "surface-variant": "#e2e3dc",
        "secondary-fixed-dim": "#e4c376",
        "on-surface": "#1a1c18",
        "on-background": "#1a1c18"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "md": "24px",
        "margin-mobile": "20px",
        "lg": "40px",
        "gutter": "16px",
        "xs": "4px",
        "xl": "64px",
        "sm": "12px",
        "base": "8px"
      },
      fontFamily: {
        "label-sm": ["Plus Jakarta Sans", "sans-serif"],
        "h2": ["Epilogue", "sans-serif"],
        "h1": ["Epilogue", "sans-serif"],
        "label-md": ["Plus Jakarta Sans", "sans-serif"],
        "body-lg": ["Plus Jakarta Sans", "sans-serif"],
        "body-md": ["Plus Jakarta Sans", "sans-serif"]
      },
      fontSize: {
        "label-sm": ["12px", { lineHeight: "1", letterSpacing: "0.05em", fontWeight: "700" }],
        "h2": ["24px", { lineHeight: "1.3", letterSpacing: "-0.01em", fontWeight: "600" }],
        "h1": ["32px", { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "700" }],
        "label-md": ["14px", { lineHeight: "1.4", letterSpacing: "0.01em", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "1.5", fontWeight: "400" }]
      }
    },
  },
  plugins: [],
}